# Generated by Django 5.2.5 on 2025-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_balancegroup_balancesheetitem_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
