# Generated by Django 5.2.5 on 2025-08-14 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_account_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, max_length=600)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("is_voided", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="MainPageModel",
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("passive", "Passive"),
                    ("active-passive", "Active-passive"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="credit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_transactions",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="debit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debit_transactions",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversed_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revers_transaction",
                to="accounting.transaction",
            ),
        ),
    ]
