# Generated by Django 5.2.5 on 2025-08-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0004_transaction_delete_mainpagemodel_alter_account_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reversed_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_transactions",
                to="accounting.transaction",
            ),
        ),
    ]
